#line 2 "lex.yy.cc"

#line 4 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 25
#define YY_END_OF_BUFFER 26
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[251] =
    {   0,
       20,   20,   26,   24,    2,    1,   24,   24,   10,   24,
        4,    3,   11,   24,   24,    6,   21,   24,   24,   11,
       24,    0,   24,   11,   24,   24,    7,    8,    5,   11,
       11,   11,   24,    0,   24,   11,   13,   24,   22,   22,
       24,   12,   12,   24,   11,   11,   11,   11,   24,    0,
       24,   13,   11,   24,    0,   24,   24,   24,   24,   11,
       24,   20,    9,   13,   24,   11,   11,   11,   11,   24,
       24,   22,   24,   24,    0,   12,   24,   11,   20,   11,
       13,   24,   11,   11,   11,   11,   20,   17,   24,   15,
       16,   24,   11,   11,   11,   11,   18,   20,   20,   20,

       24,    0,   24,   11,   13,   20,   11,   24,   23,   23,
       22,   22,   24,   20,   12,   20,   24,   11,   11,   11,
       11,   11,   20,   12,   20,   20,   24,    0,   24,   13,
       11,   20,   11,   20,   20,   20,   24,   11,   11,   11,
       11,   20,   13,   20,   24,   11,   11,   11,   11,   11,
       20,   20,   13,   20,   24,   23,   22,   23,   23,   20,
       20,   20,   20,   20,   20,   12,   20,   20,   11,   11,
       11,   11,   11,   11,   20,   13,   20,   24,   11,   11,
       11,   11,   11,   20,   20,   13,   20,   20,   24,   11,
       11,   11,   11,   20,   20,   13,   20,   11,   11,   11,

       11,   11,   11,   20,   24,   23,   20,   20,   20,   20,
       20,   11,   11,   11,   11,   11,   20,   20,   13,   20,
       11,   11,   11,   11,   11,   11,   20,   24,   11,   20,
       11,   11,   11,   11,   11,    0,   20,   11,   20,   11,
       11,   11,   11,   11,   19,   11,   14,   11,   14,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    7,    1,    8,    1,    9,
       10,    1,    1,    1,    1,    1,   11,    1,    1,   12,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   13,
        1,   14,   15,    1,    1,    1,    1,    1,   16,    1,
        1,   17,    1,    1,    1,   18,    1,    1,    1,    1,
        1,    1,   19,    1,    1,    1,    1,    1,    1,    1,
        1,   20,    1,    1,   21,   22,    1,    1,   23,    1,

       24,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       25,    1,    1,   26,   27,    1,   28,    1,    1,    1,
        1,    1,   29,   30,   31,   32,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[33] =
    {   0,
        1,    2,    3,    2,    1,    1,    1,    4,    1,    1,
        1,    1,    4,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        1,    1
    } ;

static const flex_int16_t yy_base[305] =
    {   0,
        0,    0,  291,   26, 2423, 2423,   45,   28, 2423,   31,
     2423,   26,   68,   97,   35, 2423,   43,   36,   54,  120,
      149,  284,  260,  178,  207,  237, 2423, 2423,  280,  262,
        0,  285,  314,  264,  255,  343,    0,   57,   59,   60,
      369,    0,  277,  389,  419,    0,   88,    0,  448,  271,
      251,    0,  477,  503,  247,  520,  547,   10,   55,  577,
       62,  607, 2423,  251,  637,  667,   93,    0,    0,   80,
       96,  696,  241,  726,   38,    0,  211,  756,  786,  116,
      226,  816,  846,  119,    0,    0,  875,  905,   83,    0,
        0,  108,  935,  128,    0,  965,    0,    0,  206,    0,

      995,  104,  205, 1025,    0, 1055,  139,  124,  138,  161,
     1085,  203, 1115, 1145,  107, 1175,    0, 1205,    0,  169,
        0, 1235, 1265,    0,  202,    0, 1295,  115,  201,    0,
     1325, 1355,  150, 1385,  200,    0,  147, 1415, 1445,  196,
        0,    0,  152, 1475,    0, 1505,  185,    0,    0, 1535,
     1565,  190,    0,    0,  181, 1595,    0,    0,  189, 1625,
     1655,  184, 1685,    0, 1715,    0,  174,    0,  191, 1745,
     1775,    0,  148,    0,    0,  154, 1805,    0, 1835,  192,
        0,    0, 1865, 1895,  141,    0,    0,    0,  181, 1925,
      138,    0,    0, 1955,  137,    0,    0,  202, 1985, 2015,

      119,    0,    0,    0,  267,    0,    0,  113,    0,    0,
        0, 2045,    0,  107,    0,    0, 2075,   80,    0,    0,
      275, 2105, 2135,   79,    0,    0,    0,  197,    0,    0,
     2165,   73,    0,    0,    0,    0,    0,    0,    0, 2195,
       67,    0,    0,    0,    0,    0,    0,    0,    0, 2423,
       77, 2226, 2230, 2234,   72, 2238, 2242, 2246, 2250, 2254,
     2258, 2262, 2266, 2270, 2274, 2278, 2282, 2286, 2290, 2294,
       67, 2298, 2302, 2306, 2310, 2314, 2318, 2322, 2326, 2330,
     2334, 2338, 2342, 2346, 2350, 2354, 2358, 2362, 2366, 2370,
     2374, 2378, 2382, 2386, 2390, 2394, 2398, 2402, 2406, 2410,

     2414, 2418,   61,   35
    } ;

static const flex_int16_t yy_def[305] =
    {   0,
      250,    1,  250,  251,  250,  250,  252,  251,  250,  251,
      250,  250,  253,  254,  251,  250,  255,  251,  251,  253,
      252,  256,   21,  257,  258,  250,  250,  250,  250,  253,
      259,  253,  254,  260,   33,  261,   33,  251,  255,  255,
       26,   21,  256,  262,  257,   45,  263,   45,  258,  264,
       49,   49,  265,   26,  266,   26,   26,   57,   57,  267,
       57,  268,  250,  260,  269,  261,  270,   66,   66,  251,
      271,  272,   57,  262,  273,   74,   74,  274,  275,  263,
      264,  276,  265,  277,   83,   83,  278,  268,   57,   88,
       88,   57,  267,  279,   93,  280,   88,   88,   88,   88,

      269,  281,  101,  282,  101,  283,  270,  251,  271,  271,
      272,  111,  284,  285,  273,  286,   74,  274,  118,  287,
      118,  288,  275,  123,  123,  123,  276,  289,  127,  127,
      290,  291,  277,  278,  134,  134,   57,  292,  280,  139,
      139,   88,  281,  293,  101,  282,  294,  146,  146,  295,
      283,  151,  151,  151,  251,  284,  111,  156,  156,  296,
      285,  161,  296,  161,  286,  165,  165,  165,  287,  297,
      288,  171,  171,  171,  123,  289,  298,  127,  290,  299,
      179,  179,  300,  291,  184,  184,  184,  134,   57,  292,
      190,  190,  139,  293,  194,  194,  194,  294,  301,  295,

      200,  200,  200,  151,  251,  156,  163,  163,  163,  161,
      165,  297,  212,  212,  212,  171,  298,  217,  217,  217,
      299,  302,  300,  223,  223,  223,  184,   57,  190,  194,
      301,  231,  231,  231,  200,  303,  163,  212,  217,  302,
      240,  240,  240,  223,   88,  231,  304,  240,  304,    0,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,

      250,  250,  250,  250
    } ;

static const flex_int16_t yy_nxt[2456] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,    4,    4,
        4,   10,   11,   12,    4,    4,    4,    4,    4,   13,
        4,   14,    4,    4,    4,    4,   15,    4,    4,   16,
        4,   17,   19,   28,   19,  249,   25,   19,   54,   29,
       91,   19,   19,  115,   27,   20,   22,   20,   22,   40,
       20,   23,   22,   18,   20,   20,   26,   22,   22,   38,
       19,  247,   20,   19,   24,   40,   40,  109,  116,   71,
       71,   92,   39,   20,   22,   31,   20,   18,   20,   20,
       31,   31,   41,   54,   70,   62,   19,   32,   72,   22,
       54,   22,   97,   80,   34,  248,   34,   31,   34,   20,

       34,  246,  110,   35,   34,  108,   18,  244,  239,   34,
       34,   54,  115,   62,  107,   20,   36,   22,   37,   22,
       50,   80,   50,  137,  176,  143,   34,   31,  133,   55,
       19,   55,   31,   31,  144,  238,   54,  116,   62,   32,
       34,  237,   34,   20,  110,  177,  155,  235,   18,   31,
       22,   50,   22,   50,   42,   23,   22,   20,  138,  133,
      107,   22,   22,  176,  189,  230,  229,  110,   24,  227,
       75,   18,   75,  143,  169,   54,  216,   62,   22,   22,
       20,   22,  144,   46,  177,   47,  102,   19,  102,  156,
       47,   47,   75,  128,   75,  128,  169,   48,  228,  170,

       20,  221,  211,  102,  205,  102,  198,   47,   50,   54,
       50,   62,  210,   51,   50,  199,   52,  206,  204,   50,
       50,  170,  222,  198,  193,   54,   53,  245,  188,  178,
      175,  157,  199,  145,  142,   81,   50,   54,   55,  117,
       55,   56,   54,   57,   55,   54,   54,   54,   54,   55,
       55,   58,   54,   54,   54,   59,   60,   61,   54,   54,
       54,   54,   54,   54,   54,   54,   55,   62,   54,   31,
      236,   62,   64,   19,   31,   31,  128,   87,  128,   82,
       81,   32,   43,   65,  221,   64,   20,   63,   44,   43,
      250,   31,   31,  250,  250,  250,  250,   31,   31,  250,

      250,  250,  250,  250,   32,  222,  250,  250,  250,  250,
      250,  250,  250,  250,   31,   34,  250,   34,  250,  250,
       35,   34,  250,  250,  250,  250,   34,   34,  250,  250,
      250,  250,  250,   36,  250,   37,  250,  250,  250,  250,
      250,  250,  250,   34,   34,  250,   34,  250,  250,  250,
       67,  250,  250,  250,  250,   67,   67,  250,  250,  250,
      250,  250,   68,  250,   69,  250,  250,  250,  250,  250,
      250,  250,   67,   54,  250,   73,  250,  250,  250,  250,
      250,  250,  250,   54,  250,  250,  250,   54,  250,   54,
       75,  250,   75,  250,   76,   77,   75,  250,  250,  250,

      250,   75,   75,  250,  250,  250,  250,  250,   78,  250,
      250,  250,  250,  250,  250,  250,  250,  250,   75,   79,
       22,  250,   22,  250,   46,  250,   47,  250,  250,  250,
      250,   47,   47,  250,  250,  250,  250,  250,   48,  250,
      250,  250,  250,  250,  250,  250,  250,  250,   47,   50,
      250,   50,  250,  250,   51,   50,  250,   52,  250,  250,
       50,   50,  250,  250,  250,  250,  250,   53,  250,  250,
      250,  250,  250,  250,  250,  250,  250,   50,   50,  250,
       50,  250,  250,  250,   84,  250,   85,  250,  250,   84,
       84,  250,  250,  250,  250,  250,   86,  250,  250,  250,

      250,  250,  250,  250,  250,  250,   84,   54,  250,   73,
      250,  250,  250,  250,  250,  250,  250,   54,  250,  250,
      250,   54,  250,   54,   54,  250,   73,  250,  250,  250,
      250,  250,  250,  250,   54,  250,  250,  250,   54,  250,
       54,  250,  250,  250,  250,  250,  250,  250,  250,  250,
       88,   54,  250,   73,  250,  250,  250,  250,  250,  250,
      250,   54,  250,  250,  250,   54,  250,   54,  250,  250,
      250,  250,  250,  250,  250,   89,  250,   90,   55,  250,
       55,  250,  250,  250,   94,  250,  250,  250,  250,   94,
       94,  250,  250,  250,  250,  250,   95,  250,  250,  250,

      250,  250,  250,  250,  250,  250,   94,   96,   55,  250,
       55,  250,  250,   99,   55,  250,  250,  250,  250,   55,
       55,  250,  250,  250,  250,  250,   60,  250,  250,  250,
      250,  250,  250,  250,  250,  250,   55,  100,  102,  250,
      102,  250,  250,  103,  102,  250,  250,  250,  250,  102,
      102,  250,  250,  250,  250,  250,  104,  250,  105,  250,
      250,  250,  250,  250,  250,  250,  102,  106,   34,  250,
       34,  250,  250,  250,   67,  250,  250,  250,  250,   67,
       67,  250,  250,  250,  250,  250,   68,  250,   69,  250,
      250,  250,  250,  250,  250,  250,   67,   55,  250,   55,

      250,  250,  112,   55,  250,  250,  113,  250,   55,   55,
      250,  250,  250,  250,  250,   60,  250,  250,  250,  250,
      250,  250,  250,  250,  250,   55,  114,   75,  250,   75,
      250,   76,   77,   75,  250,  250,  250,  250,   75,   75,
      250,  250,  250,  250,  250,   78,  250,  250,  250,  250,
      250,  250,  250,  250,  250,   75,   79,   75,  250,   75,
      250,  119,  250,  120,  250,  250,  250,  250,  120,  120,
      250,  250,  250,  250,  250,  121,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  120,  122,   75,  250,   75,
      250,  124,  125,   75,  250,  250,  250,  250,   75,   75,

      250,  250,  250,  250,  250,   78,  250,  250,  250,  250,
      250,  250,  250,  250,  250,   75,  126,  128,  250,  128,
      250,  250,  129,  128,  250,  130,  250,  250,  128,  128,
      250,  250,  250,  250,  250,  131,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  128,  132,   50,  250,   50,
      250,  250,  250,   84,  250,   85,  250,  250,   84,   84,
      250,  250,  250,  250,  250,   86,  250,  250,  250,  250,
      250,  250,  250,  250,  250,   84,   55,  250,   55,  250,
      250,  135,   55,  250,  250,  250,  250,   55,   55,  250,
      250,  250,  250,  250,   55,  250,  250,  250,  250,  250,

      250,  250,  250,  250,   55,  136,   55,  250,   55,  250,
      250,   99,   55,  250,  250,  250,  250,   55,   55,  250,
      250,  250,  250,  250,   60,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   55,  100,   55,  250,   55,  250,
      250,  250,   94,  250,  250,  250,  250,   94,   94,  250,
      250,  250,  250,  250,   95,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   94,   96,   55,  250,   55,  250,
      250,  140,   94,  250,  250,  250,  250,   94,   94,  250,
      250,  250,  250,  250,   95,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   94,  141,  102,  250,  102,  250,

      250,  103,  102,  250,  250,  250,  250,  102,  102,  250,
      250,  250,  250,  250,  104,  250,  105,  250,  250,  250,
      250,  250,  250,  250,  102,  106,  102,  250,  102,  250,
      250,  250,  147,  250,  250,  250,  250,  147,  147,  250,
      250,  250,  250,  250,  148,  250,  149,  250,  250,  250,
      250,  250,  250,  250,  147,  150,  102,  250,  102,  250,
      250,  152,  102,  250,  250,  250,  250,  102,  102,  250,
      250,  250,  250,  250,  104,  250,  153,  250,  250,  250,
      250,  250,  250,  250,  102,  154,   55,  250,   55,  250,
      250,  112,   55,  250,  250,  113,  250,   55,   55,  250,

      250,  250,  250,  250,   60,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   55,  114,   55,  250,   55,  250,
      250,  159,   55,  250,  250,   54,  250,   55,   55,  250,
      250,  250,  250,  250,   60,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   55,  160,   55,  250,   55,  250,
      250,  162,   55,  250,  250,  163,  250,   55,   55,  250,
      250,  250,  250,  250,   60,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   55,  164,   75,  250,   75,  250,
      166,  167,   75,  250,  250,  250,  250,   75,   75,  250,
      250,  250,  250,  250,   75,  250,  250,  250,  250,  250,

      250,  250,  250,  250,   75,  168,   75,  250,   75,  250,
      119,  250,  120,  250,  250,  250,  250,  120,  120,  250,
      250,  250,  250,  250,  121,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  120,  122,   75,  250,   75,  250,
      172,  173,  120,  250,  250,  250,  250,  120,  120,  250,
      250,  250,  250,  250,  121,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  120,  174,   75,  250,   75,  250,
      124,  125,   75,  250,  250,  250,  250,   75,   75,  250,
      250,  250,  250,  250,   78,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   75,  126,  128,  250,  128,  250,

      250,  129,  128,  250,  130,  250,  250,  128,  128,  250,
      250,  250,  250,  250,  131,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  128,  132,  128,  250,  128,  250,
      250,  250,  180,  250,  181,  250,  250,  180,  180,  250,
      250,  250,  250,  250,  182,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  180,  183,  128,  250,  128,  250,
      250,  185,  128,  250,  186,  250,  250,  128,  128,  250,
      250,  250,  250,  250,  131,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  128,  187,   55,  250,   55,  250,
      250,  135,   55,  250,  250,  250,  250,   55,   55,  250,

      250,  250,  250,  250,   55,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   55,  136,   55,  250,   55,  250,
      250,  191,   94,  250,  250,  250,  250,   94,   94,  250,
      250,  250,  250,  250,   94,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   94,  192,   55,  250,   55,  250,
      250,  140,   94,  250,  250,  250,  250,   94,   94,  250,
      250,  250,  250,  250,   95,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   94,  141,  102,  250,  102,  250,
      250,  195,  102,  250,  250,  250,  250,  102,  102,  250,
      250,  250,  250,  250,  102,  250,  196,  250,  250,  250,

      250,  250,  250,  250,  102,  197,  102,  250,  102,  250,
      250,  250,  147,  250,  250,  250,  250,  147,  147,  250,
      250,  250,  250,  250,  148,  250,  149,  250,  250,  250,
      250,  250,  250,  250,  147,  150,  102,  250,  102,  250,
      250,  201,  147,  250,  250,  250,  250,  147,  147,  250,
      250,  250,  250,  250,  148,  250,  202,  250,  250,  250,
      250,  250,  250,  250,  147,  203,  102,  250,  102,  250,
      250,  152,  102,  250,  250,  250,  250,  102,  102,  250,
      250,  250,  250,  250,  104,  250,  153,  250,  250,  250,
      250,  250,  250,  250,  102,  154,   55,  250,   55,  250,

      250,  159,   55,  250,  250,   54,  250,   55,   55,  250,
      250,  250,  250,  250,   60,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   55,  160,   55,  250,   55,  250,
      250,  208,   55,  250,  250,   98,  250,   55,   55,  250,
      250,  250,  250,  250,   60,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   55,  209,   55,  250,   55,  250,
      250,  162,   55,  250,  250,  163,  250,   55,   55,  250,
      250,  250,  250,  250,   60,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   55,  164,   55,  250,   55,  250,
      250,  208,   55,  250,  250,   98,  250,   55,   55,  250,

      250,  250,  250,  250,   60,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   55,  209,   75,  250,   75,  250,
      166,  167,   75,  250,  250,  250,  250,   75,   75,  250,
      250,  250,  250,  250,   75,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   75,  168,   75,  250,   75,  250,
      213,  214,  120,  250,  250,  250,  250,  120,  120,  250,
      250,  250,  250,  250,  120,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  120,  215,   75,  250,   75,  250,
      172,  173,  120,  250,  250,  250,  250,  120,  120,  250,
      250,  250,  250,  250,  121,  250,  250,  250,  250,  250,

      250,  250,  250,  250,  120,  174,  128,  250,  128,  250,
      250,  218,  128,  250,  219,  250,  250,  128,  128,  250,
      250,  250,  250,  250,  128,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  128,  220,  128,  250,  128,  250,
      250,  250,  180,  250,  181,  250,  250,  180,  180,  250,
      250,  250,  250,  250,  182,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  180,  183,  128,  250,  128,  250,
      250,  224,  180,  250,  225,  250,  250,  180,  180,  250,
      250,  250,  250,  250,  182,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  180,  226,  128,  250,  128,  250,

      250,  185,  128,  250,  186,  250,  250,  128,  128,  250,
      250,  250,  250,  250,  131,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  128,  187,   55,  250,   55,  250,
      250,  191,   94,  250,  250,  250,  250,   94,   94,  250,
      250,  250,  250,  250,   94,  250,  250,  250,  250,  250,
      250,  250,  250,  250,   94,  192,  102,  250,  102,  250,
      250,  195,  102,  250,  250,  250,  250,  102,  102,  250,
      250,  250,  250,  250,  102,  250,  196,  250,  250,  250,
      250,  250,  250,  250,  102,  197,  102,  250,  102,  250,
      250,  232,  147,  250,  250,  250,  250,  147,  147,  250,

      250,  250,  250,  250,  147,  250,  233,  250,  250,  250,
      250,  250,  250,  250,  147,  234,  102,  250,  102,  250,
      250,  201,  147,  250,  250,  250,  250,  147,  147,  250,
      250,  250,  250,  250,  148,  250,  202,  250,  250,  250,
      250,  250,  250,  250,  147,  203,   75,  250,   75,  250,
      213,  214,  120,  250,  250,  250,  250,  120,  120,  250,
      250,  250,  250,  250,  120,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  120,  215,  128,  250,  128,  250,
      250,  218,  128,  250,  219,  250,  250,  128,  128,  250,
      250,  250,  250,  250,  128,  250,  250,  250,  250,  250,

      250,  250,  250,  250,  128,  220,  128,  250,  128,  250,
      250,  241,  180,  250,  242,  250,  250,  180,  180,  250,
      250,  250,  250,  250,  180,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  180,  243,  128,  250,  128,  250,
      250,  224,  180,  250,  225,  250,  250,  180,  180,  250,
      250,  250,  250,  250,  182,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  180,  226,  102,  250,  102,  250,
      250,  232,  147,  250,  250,  250,  250,  147,  147,  250,
      250,  250,  250,  250,  147,  250,  233,  250,  250,  250,
      250,  250,  250,  250,  147,  234,  128,  250,  128,  250,

      250,  241,  180,  250,  242,  250,  250,  180,  180,  250,
      250,  250,  250,  250,  180,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  180,  243,   21,   21,  250,   21,
       30,  250,  250,   30,   33,   33,  250,   33,   22,   22,
      250,   22,   45,   45,  250,   45,   49,   49,  250,   49,
       31,  250,  250,   31,   34,   34,  250,   34,   66,   66,
      250,   66,   74,   74,  250,   74,   47,   47,  250,   47,
       50,   50,  250,   50,   83,   83,  250,   83,   55,   55,
      250,   55,   93,   93,  250,   93,   98,   98,  250,   98,
      101,  101,  250,  101,   67,   67,  250,   67,  111,  111,

      250,  111,   75,   75,  250,   75,  118,  118,  250,  118,
      123,  123,  250,  123,  127,  127,  250,  127,   84,   84,
      250,   84,  134,  134,  250,  134,   94,   94,  250,   94,
      139,  139,  250,  139,  102,  102,  250,  102,  146,  146,
      250,  146,  151,  151,  250,  151,  158,  158,  250,  158,
      161,  161,  250,  161,  165,  165,  250,  165,  120,  120,
      250,  120,  171,  171,  250,  171,  128,  128,  250,  128,
      179,  179,  250,  179,  184,  184,  250,  184,  190,  190,
      250,  190,  194,  194,  250,  194,  147,  147,  250,  147,
      200,  200,  250,  200,  207,  207,  250,  207,  212,  212,

      250,  212,  217,  217,  250,  217,  180,  180,  250,  180,
      223,  223,  250,  223,  231,  231,  250,  231,  240,  240,
      250,  240,    3,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250
    } ;

static const flex_int16_t yy_chk[2456] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,   12,    8,  304,    8,   10,   58,   12,
       58,   15,   18,   75,   10,    4,    7,    8,    7,   17,
       10,    7,    7,   17,   15,   18,    8,    7,    7,   15,
       19,  303,   17,   38,    7,   39,   40,  271,   75,   39,
       40,   59,  255,   19,    7,   13,   38,  251,   39,   40,
       13,   13,   19,   59,   38,   59,   70,   13,   40,   47,
       61,   47,   61,   47,   67,  241,   67,   13,   14,   70,

       14,  232,   71,   14,   14,   70,   71,  224,  218,   14,
       14,   89,  115,   89,   67,   71,   14,   80,   14,   80,
       84,   80,   84,   92,  128,  102,   14,   20,   84,   94,
      108,   94,   20,   20,  102,  214,   92,  115,   92,   20,
      107,  208,  107,  108,  109,  128,  108,  201,  109,   20,
       21,  133,   21,  133,   21,   21,   21,  109,   94,  133,
      107,   21,   21,  176,  137,  195,  191,  110,   21,  185,
      120,  110,  120,  143,  120,  137,  173,  137,   21,   24,
      110,   24,  143,   24,  176,   24,  147,  155,  147,  110,
       24,   24,  169,  180,  169,  180,  169,   24,  189,  120,

      155,  180,  167,  198,  155,  198,  147,   24,   25,  189,
       25,  189,  162,   25,   25,  147,   25,  159,  152,   25,
       25,  169,  180,  198,  140,  228,   25,  228,  135,  129,
      125,  112,  198,  103,   99,   81,   25,   26,   26,   77,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   30,
      205,   73,   64,  205,   30,   30,  221,   55,  221,   51,
       50,   30,   43,   35,  221,   34,  205,   29,   23,   22,
        3,   30,   32,    0,    0,    0,    0,   32,   32,    0,

        0,    0,    0,    0,   32,  221,    0,    0,    0,    0,
        0,    0,    0,    0,   32,   33,    0,   33,    0,    0,
       33,   33,    0,    0,    0,    0,   33,   33,    0,    0,
        0,    0,    0,   33,    0,   33,    0,    0,    0,    0,
        0,    0,    0,   33,   36,    0,   36,    0,    0,    0,
       36,    0,    0,    0,    0,   36,   36,    0,    0,    0,
        0,    0,   36,    0,   36,    0,    0,    0,    0,    0,
        0,    0,   36,   41,    0,   41,    0,    0,    0,    0,
        0,    0,    0,   41,    0,    0,    0,   41,    0,   41,
       44,    0,   44,    0,   44,   44,   44,    0,    0,    0,

        0,   44,   44,    0,    0,    0,    0,    0,   44,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   44,   44,
       45,    0,   45,    0,   45,    0,   45,    0,    0,    0,
        0,   45,   45,    0,    0,    0,    0,    0,   45,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   45,   49,
        0,   49,    0,    0,   49,   49,    0,   49,    0,    0,
       49,   49,    0,    0,    0,    0,    0,   49,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   49,   53,    0,
       53,    0,    0,    0,   53,    0,   53,    0,    0,   53,
       53,    0,    0,    0,    0,    0,   53,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   53,   54,    0,   54,
        0,    0,    0,    0,    0,    0,    0,   54,    0,    0,
        0,   54,    0,   54,   56,    0,   56,    0,    0,    0,
        0,    0,    0,    0,   56,    0,    0,    0,   56,    0,
       56,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       56,   57,    0,   57,    0,    0,    0,    0,    0,    0,
        0,   57,    0,    0,    0,   57,    0,   57,    0,    0,
        0,    0,    0,    0,    0,   57,    0,   57,   60,    0,
       60,    0,    0,    0,   60,    0,    0,    0,    0,   60,
       60,    0,    0,    0,    0,    0,   60,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   60,   60,   62,    0,
       62,    0,    0,   62,   62,    0,    0,    0,    0,   62,
       62,    0,    0,    0,    0,    0,   62,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   62,   62,   65,    0,
       65,    0,    0,   65,   65,    0,    0,    0,    0,   65,
       65,    0,    0,    0,    0,    0,   65,    0,   65,    0,
        0,    0,    0,    0,    0,    0,   65,   65,   66,    0,
       66,    0,    0,    0,   66,    0,    0,    0,    0,   66,
       66,    0,    0,    0,    0,    0,   66,    0,   66,    0,
        0,    0,    0,    0,    0,    0,   66,   72,    0,   72,

        0,    0,   72,   72,    0,    0,   72,    0,   72,   72,
        0,    0,    0,    0,    0,   72,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   72,   72,   74,    0,   74,
        0,   74,   74,   74,    0,    0,    0,    0,   74,   74,
        0,    0,    0,    0,    0,   74,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   74,   74,   78,    0,   78,
        0,   78,    0,   78,    0,    0,    0,    0,   78,   78,
        0,    0,    0,    0,    0,   78,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   78,   78,   79,    0,   79,
        0,   79,   79,   79,    0,    0,    0,    0,   79,   79,

        0,    0,    0,    0,    0,   79,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   79,   79,   82,    0,   82,
        0,    0,   82,   82,    0,   82,    0,    0,   82,   82,
        0,    0,    0,    0,    0,   82,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   82,   82,   83,    0,   83,
        0,    0,    0,   83,    0,   83,    0,    0,   83,   83,
        0,    0,    0,    0,    0,   83,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   83,   87,    0,   87,    0,
        0,   87,   87,    0,    0,    0,    0,   87,   87,    0,
        0,    0,    0,    0,   87,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   87,   87,   88,    0,   88,    0,
        0,   88,   88,    0,    0,    0,    0,   88,   88,    0,
        0,    0,    0,    0,   88,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   88,   88,   93,    0,   93,    0,
        0,    0,   93,    0,    0,    0,    0,   93,   93,    0,
        0,    0,    0,    0,   93,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   93,   93,   96,    0,   96,    0,
        0,   96,   96,    0,    0,    0,    0,   96,   96,    0,
        0,    0,    0,    0,   96,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   96,   96,  101,    0,  101,    0,

        0,  101,  101,    0,    0,    0,    0,  101,  101,    0,
        0,    0,    0,    0,  101,    0,  101,    0,    0,    0,
        0,    0,    0,    0,  101,  101,  104,    0,  104,    0,
        0,    0,  104,    0,    0,    0,    0,  104,  104,    0,
        0,    0,    0,    0,  104,    0,  104,    0,    0,    0,
        0,    0,    0,    0,  104,  104,  106,    0,  106,    0,
        0,  106,  106,    0,    0,    0,    0,  106,  106,    0,
        0,    0,    0,    0,  106,    0,  106,    0,    0,    0,
        0,    0,    0,    0,  106,  106,  111,    0,  111,    0,
        0,  111,  111,    0,    0,  111,    0,  111,  111,    0,

        0,    0,    0,    0,  111,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  111,  111,  113,    0,  113,    0,
        0,  113,  113,    0,    0,  113,    0,  113,  113,    0,
        0,    0,    0,    0,  113,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  113,  113,  114,    0,  114,    0,
        0,  114,  114,    0,    0,  114,    0,  114,  114,    0,
        0,    0,    0,    0,  114,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  114,  114,  116,    0,  116,    0,
      116,  116,  116,    0,    0,    0,    0,  116,  116,    0,
        0,    0,    0,    0,  116,    0,    0,    0,    0,    0,

        0,    0,    0,    0,  116,  116,  118,    0,  118,    0,
      118,    0,  118,    0,    0,    0,    0,  118,  118,    0,
        0,    0,    0,    0,  118,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  118,  118,  122,    0,  122,    0,
      122,  122,  122,    0,    0,    0,    0,  122,  122,    0,
        0,    0,    0,    0,  122,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  122,  122,  123,    0,  123,    0,
      123,  123,  123,    0,    0,    0,    0,  123,  123,    0,
        0,    0,    0,    0,  123,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  123,  123,  127,    0,  127,    0,

        0,  127,  127,    0,  127,    0,    0,  127,  127,    0,
        0,    0,    0,    0,  127,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  127,  127,  131,    0,  131,    0,
        0,    0,  131,    0,  131,    0,    0,  131,  131,    0,
        0,    0,    0,    0,  131,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  131,  131,  132,    0,  132,    0,
        0,  132,  132,    0,  132,    0,    0,  132,  132,    0,
        0,    0,    0,    0,  132,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  132,  132,  134,    0,  134,    0,
        0,  134,  134,    0,    0,    0,    0,  134,  134,    0,

        0,    0,    0,    0,  134,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  134,  134,  138,    0,  138,    0,
        0,  138,  138,    0,    0,    0,    0,  138,  138,    0,
        0,    0,    0,    0,  138,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  138,  138,  139,    0,  139,    0,
        0,  139,  139,    0,    0,    0,    0,  139,  139,    0,
        0,    0,    0,    0,  139,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  139,  139,  144,    0,  144,    0,
        0,  144,  144,    0,    0,    0,    0,  144,  144,    0,
        0,    0,    0,    0,  144,    0,  144,    0,    0,    0,

        0,    0,    0,    0,  144,  144,  146,    0,  146,    0,
        0,    0,  146,    0,    0,    0,    0,  146,  146,    0,
        0,    0,    0,    0,  146,    0,  146,    0,    0,    0,
        0,    0,    0,    0,  146,  146,  150,    0,  150,    0,
        0,  150,  150,    0,    0,    0,    0,  150,  150,    0,
        0,    0,    0,    0,  150,    0,  150,    0,    0,    0,
        0,    0,    0,    0,  150,  150,  151,    0,  151,    0,
        0,  151,  151,    0,    0,    0,    0,  151,  151,    0,
        0,    0,    0,    0,  151,    0,  151,    0,    0,    0,
        0,    0,    0,    0,  151,  151,  156,    0,  156,    0,

        0,  156,  156,    0,    0,  156,    0,  156,  156,    0,
        0,    0,    0,    0,  156,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  156,  156,  160,    0,  160,    0,
        0,  160,  160,    0,    0,  160,    0,  160,  160,    0,
        0,    0,    0,    0,  160,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  160,  160,  161,    0,  161,    0,
        0,  161,  161,    0,    0,  161,    0,  161,  161,    0,
        0,    0,    0,    0,  161,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  161,  161,  163,    0,  163,    0,
        0,  163,  163,    0,    0,  163,    0,  163,  163,    0,

        0,    0,    0,    0,  163,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  163,  163,  165,    0,  165,    0,
      165,  165,  165,    0,    0,    0,    0,  165,  165,    0,
        0,    0,    0,    0,  165,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  165,  165,  170,    0,  170,    0,
      170,  170,  170,    0,    0,    0,    0,  170,  170,    0,
        0,    0,    0,    0,  170,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  170,  170,  171,    0,  171,    0,
      171,  171,  171,    0,    0,    0,    0,  171,  171,    0,
        0,    0,    0,    0,  171,    0,    0,    0,    0,    0,

        0,    0,    0,    0,  171,  171,  177,    0,  177,    0,
        0,  177,  177,    0,  177,    0,    0,  177,  177,    0,
        0,    0,    0,    0,  177,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  177,  177,  179,    0,  179,    0,
        0,    0,  179,    0,  179,    0,    0,  179,  179,    0,
        0,    0,    0,    0,  179,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  179,  179,  183,    0,  183,    0,
        0,  183,  183,    0,  183,    0,    0,  183,  183,    0,
        0,    0,    0,    0,  183,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  183,  183,  184,    0,  184,    0,

        0,  184,  184,    0,  184,    0,    0,  184,  184,    0,
        0,    0,    0,    0,  184,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  184,  184,  190,    0,  190,    0,
        0,  190,  190,    0,    0,    0,    0,  190,  190,    0,
        0,    0,    0,    0,  190,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  190,  190,  194,    0,  194,    0,
        0,  194,  194,    0,    0,    0,    0,  194,  194,    0,
        0,    0,    0,    0,  194,    0,  194,    0,    0,    0,
        0,    0,    0,    0,  194,  194,  199,    0,  199,    0,
        0,  199,  199,    0,    0,    0,    0,  199,  199,    0,

        0,    0,    0,    0,  199,    0,  199,    0,    0,    0,
        0,    0,    0,    0,  199,  199,  200,    0,  200,    0,
        0,  200,  200,    0,    0,    0,    0,  200,  200,    0,
        0,    0,    0,    0,  200,    0,  200,    0,    0,    0,
        0,    0,    0,    0,  200,  200,  212,    0,  212,    0,
      212,  212,  212,    0,    0,    0,    0,  212,  212,    0,
        0,    0,    0,    0,  212,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  212,  212,  217,    0,  217,    0,
        0,  217,  217,    0,  217,    0,    0,  217,  217,    0,
        0,    0,    0,    0,  217,    0,    0,    0,    0,    0,

        0,    0,    0,    0,  217,  217,  222,    0,  222,    0,
        0,  222,  222,    0,  222,    0,    0,  222,  222,    0,
        0,    0,    0,    0,  222,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  222,  222,  223,    0,  223,    0,
        0,  223,  223,    0,  223,    0,    0,  223,  223,    0,
        0,    0,    0,    0,  223,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  223,  223,  231,    0,  231,    0,
        0,  231,  231,    0,    0,    0,    0,  231,  231,    0,
        0,    0,    0,    0,  231,    0,  231,    0,    0,    0,
        0,    0,    0,    0,  231,  231,  240,    0,  240,    0,

        0,  240,  240,    0,  240,    0,    0,  240,  240,    0,
        0,    0,    0,    0,  240,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  240,  240,  252,  252,    0,  252,
      253,    0,    0,  253,  254,  254,    0,  254,  256,  256,
        0,  256,  257,  257,    0,  257,  258,  258,    0,  258,
      259,    0,    0,  259,  260,  260,    0,  260,  261,  261,
        0,  261,  262,  262,    0,  262,  263,  263,    0,  263,
      264,  264,    0,  264,  265,  265,    0,  265,  266,  266,
        0,  266,  267,  267,    0,  267,  268,  268,    0,  268,
      269,  269,    0,  269,  270,  270,    0,  270,  272,  272,

        0,  272,  273,  273,    0,  273,  274,  274,    0,  274,
      275,  275,    0,  275,  276,  276,    0,  276,  277,  277,
        0,  277,  278,  278,    0,  278,  279,  279,    0,  279,
      280,  280,    0,  280,  281,  281,    0,  281,  282,  282,
        0,  282,  283,  283,    0,  283,  284,  284,    0,  284,
      285,  285,    0,  285,  286,  286,    0,  286,  287,  287,
        0,  287,  288,  288,    0,  288,  289,  289,    0,  289,
      290,  290,    0,  290,  291,  291,    0,  291,  292,  292,
        0,  292,  293,  293,    0,  293,  294,  294,    0,  294,
      295,  295,    0,  295,  296,  296,    0,  296,  297,  297,

        0,  297,  298,  298,    0,  298,  299,  299,    0,  299,
      300,  300,    0,  300,  301,  301,    0,  301,  302,  302,
        0,  302,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[26] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "shell.l"
/*
 *
 * CS-252 
 * shell.l: lexical analyzer for shell
 * You have to extend it.
 *
 */
#line 11 "shell.l"

#include <cstring>
#include "y.tab.hh"
#include <string>

#include <unistd.h>

#include <fcntl.h>
#include <sys/types.h>
#include <stdlib.h>
#include <limits.h>
#include <iostream>
#include <sys/wait.h>
#include <regex>
#include <pwd.h>

extern int * returnCode;
extern pid_t * bgPID;
extern std::string * lastArg;
extern char * path_argv;

static  void yyunput (int c,char *buf_ptr  );

void myunputc(int c) {
  unput(c);
}

////////////  Start added code ///////////
extern "C" char * read_line();

int mygetc(FILE * f) {
 static char *p;
 char ch;

 if (!isatty(0)) {
 // stdin is not a tty. Call real getc
   return getc(f);
 }

 // stdin is a tty. Call our read_line.
 if (p==NULL || *p == 0) {
   char * s = read_line();
   p = s;
 }

 ch = *p;
 p++;

 return ch;
}

#undef getc
#define getc(f) mygetc(f)

/////////// End added code ///////////

#line 1170 "lex.yy.cc"
#line 1171 "lex.yy.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 71 "shell.l"


#line 1391 "lex.yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 251 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2423 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 73 "shell.l"
{
  return NEWLINE;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 77 "shell.l"
{
  /* Discard spaces and tabs */
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 81 "shell.l"
{
  return GREAT;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 85 "shell.l"
{
  return LESS;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 89 "shell.l"
{
  return GREAT_GREAT;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 93 "shell.l"
{
  return PIPE;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 97 "shell.l"
{
  return TWO_GREAT;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 101 "shell.l"
{
  return GREAT_AMPERSAND;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 105 "shell.l"
{
  return GREAT_GREAT_AMPERSAND;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 109 "shell.l"
{
  return AMPERSAND;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 113 "shell.l"
{ //escape old:(([^ \\\t\n<>|&]*\\.[^ \\\t\n<>|&]*)*)
  char * temp = yytext;
  char newStr[500];
  int index = 0;
  int i = 0;

  for (i = 0; i < strlen(temp); i++) {
    if (temp[i] == '\\') {
      newStr[index] = temp[i + 1];
      index++;
      i++;
    } else {
      newStr[index] = temp[i];
      index++;
    }
  }

  newStr[index] = '\0';
  yylval.cpp_string = new std::string(newStr);
  return WORD;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 135 "shell.l"
{ //quotes
  std::string temp = yytext;
  int end = temp.size()-2;
  temp = temp.substr(1, end);
  yylval.cpp_string = new std::string(temp);
  return WORD;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 143 "shell.l"
{ //subshell
  std::string temp(yytext);
  if (temp.find("`") == 0) {
    temp = temp.substr(1, temp.size()-2);
  } else {
    temp = temp.substr(2, temp.size()-3);
  }
  temp.append("\nexit\n");

  int tmpin = dup(0);
  int tmpout = dup(1);
  int PIN[2];
  pipe(PIN);
  int POUT[2];
  pipe(POUT);

  write(PIN[1], temp.c_str(), temp.size());
  close(PIN[1]);
  dup2(PIN[0],0);
  close(PIN[0]);
  dup2(POUT[1],1);
  close(POUT[1]);

  int ret = fork();
  if (ret == 0) {
    execlp("/proc/self/exe", "/proc/self/exe", NULL);
    perror("");
    exit(-1);
  }

  //restore in/out defaults
  dup2(tmpin, 0);
  dup2(tmpout, 1);
  close(tmpin);
  close(tmpout);

  char bufferString[1024];    //size can be changed
  int bufferLength = read(POUT[0],bufferString, 1024);
  bufferString[bufferLength] = '\0';
  std::string returnString(bufferString);

  //remove "\n"
  while (returnString.find("\n") != -1) {
    int i = returnString.find("\n");
    returnString.replace(i, 1, " ");
  }

  //put back to main shell using myunputc
  const char * putbackString = returnString.c_str();
  int forLen = returnString.size();
  for (int i = forLen - 1; i >= 0; i--) {
    myunputc(putbackString[i]);
  }
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 198 "shell.l"
{ //source BUILD-IN
  char * raw_file = yytext + 7;
  int inFile = open(raw_file, O_RDONLY);
  char bufferTemp[1024];
  int bufferLen = read(inFile, bufferTemp, 1024);
  bufferTemp[bufferLen] = '\0';
  std::string buffer(bufferTemp);

  //remove "\n"
  while (buffer.find("\n") != -1) {
    int i = buffer.find("\n");
    buffer.replace(i, 1, " ");
  }
  //put back to main shell using myunputc
  const char * putbackString = buffer.c_str();
  int forLen = buffer.size();
  for (int i = forLen - 1; i >= 0; i--) {
    myunputc(putbackString[i]);
  }
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 219 "shell.l"
{ //${$} The PID of the shell process
  int pid = getpid();
  std::string pid_str = std::to_string(pid);
  yylval.cpp_string = new std::string(pid_str);
  return WORD;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 226 "shell.l"
{ //${?} The return code of the last executed simple command
  int num = *returnCode;
  std::string num_str = std::to_string(num);
  yylval.cpp_string = new std::string(num_str);
  return WORD;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 233 "shell.l"
{ //${!} PID of the last process run in the background
  int pid = *bgPID;
  std::string pid_str = std::to_string(pid);
  yylval.cpp_string = new std::string(pid_str);
  return WORD;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 240 "shell.l"
{ //${_} The last argument in the fully expanded previous command
  yylval.cpp_string = new std::string(* lastArg);
  return WORD;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 245 "shell.l"
{ //${SHELL} The path of your shell executable.
  char absPath[1024];
  realpath(path_argv, absPath);
  yylval.cpp_string = new std::string(absPath);
  return WORD;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 252 "shell.l"
{ //env var expansion
  using namespace std;
  string *temp = new string(yytext);
  while (regex_search(*temp, regex("([$][{].*?[}])")) ) {
    smatch sm;
    regex_search(*temp, sm, regex("([$][{].*?[}])"));
    string envName = sm.str(0).substr(2, sm.str(0).size() - 3);
    *temp = regex_replace(*temp, regex("([$][{].*?[}])"), getenv(envName.c_str()), regex_constants::format_first_only);
  }
  yylval.cpp_string = new std::string(*temp);
  return WORD;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 265 "shell.l"
{ //Tilde: list the home directory
  struct passwd *pws;
  pws = getpwuid(geteuid());
  yylval.cpp_string = new std::string(pws->pw_dir);
  return WORD;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 272 "shell.l"
{ //Tilde: List [george]'s home directory
  std::string temp(yytext);
  std::string user = temp.substr(1, temp.size() - 1);
  struct passwd *pws;
  pws = getpwnam(user.c_str());
  if (pws == NULL) {
    yylval.cpp_string = new std::string(yytext);
    return WORD;
  }
  yylval.cpp_string = new std::string(pws->pw_dir);
  return WORD;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 285 "shell.l"
{
  std::string temp(yytext);
  int pos1 = temp.find('/');
  std::string user = temp.substr(1, pos1-1);
  std::string dir = temp.substr(pos1+1, temp.size() - 1);
  struct passwd *pws;
  pws = getpwnam(user.c_str());
  if (pws == NULL) {
    yylval.cpp_string = new std::string(yytext);
    return WORD;
  }
  std::string tempStr(pws->pw_dir);
  tempStr.append("/");
  tempStr.append(dir);
  yylval.cpp_string = new std::string(tempStr);
  return WORD;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 303 "shell.l"
{
  /* Assume that file names have only alpha chars */
  yylval.cpp_string = new std::string(yytext);
  return WORD;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 308 "shell.l"
ECHO;
	YY_BREAK
#line 1772 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 251 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 251 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 250);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 308 "shell.l"
